kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${APP_NAME}
  namespace: ${PROJECT_NAME}
  labels:
    app: ${APP_NAME}
    component: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
      component: php
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        component: php
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: volume-php-config
          configMap:
            name: ${APP_NAME}-php-config
            items:
              - key: php.ini
                path: php.ini
              - key: php-fpm.conf
                path: php-fpm.conf
              - key: www.conf
                path: www.conf
            defaultMode: 420
        - name: volume-nginx-config
          configMap:
            name: ${APP_NAME}-nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: www.conf
                path: www.conf
            defaultMode: 420
        - name: volume-code
          emptyDir: {}
      imagePullSecrets:
        - name: default-secret
      initContainers:
        - name: ${APP_NAME}-code
          image: $REGISTRY/$PROJECT_NAME/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 20Mi
          volumeMounts:
            - name: volume-code
              mountPath: /data/www
          imagePullPolicy: IfNotPresent
      containers:
        - name: ${APP_NAME}-fpm
          image: ${REGISTRY}/library/emp-php-fpm:5.6.37
          ports:
            - name: http-0
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 3500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: volume-code
              mountPath: /data/www/
            - name: volume-php-config
              readOnly: true
              mountPath: /usr/local/services/${PHP_VERSION}/etc/php.ini
              subPath: php.ini
            - name: volume-php-config
              readOnly: true
              mountPath: /usr/local/services/${PHP_VERSION}/etc/php-fpm.d/www.conf
              subPath: www.conf
            - name: volume-php-config
              readOnly: true
              mountPath: /usr/local/services/${PHP_VERSION}/etc/php-fpm.conf
              subPath: php-fpm.conf
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          livenessProbe:
            httpGet:
              path: /php-fpm-stats
              port: 80
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          imagePullPolicy: IfNotPresent
        - name: nginx
          image: ${REGISTRY}/library/centos7.9:tengine-2.3.2
          ports:
            - name: http-1
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - name: volume-code
              mountPath: /data/www/
            - name: volume-nginx-config
              readOnly: true
              mountPath: /usr/local/services/tengine/conf/nginx.conf
              subPath: nginx.conf
            - name: volume-nginx-config
              readOnly: true
              mountPath: >-
                /usr/local/services/tengine/conf/sites-enabled/${APP_NAME}.conf
              subPath: www.conf
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          livenessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 80
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: ${APP_NAME}
                    component: php
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
